### ISSUE TITLE
Can you add the BOM to the repo? 

### ISSUE THREAD

**Issue by devsecfranklin** [lozaning/The_Wifydra#1]
curious to see what components were used.

**Comment by lozaning** [comment]
Im in the process of remaking this with different chips. Once I've finished the design and verified it works I'll update the code and include the BOM.

**Comment by turnkit** [comment]
any update on a BOM (or the XL BOM?)

Is the goal to open source the whole project so somebody else could make these for re-sell?  I'd like to see the cost as I'd like to have one.

**Comment by lozaning** [comment]
The readme has been updated with the BOM, the new gerbers, an updated readme and new Dom and Sub code. LMK if you've got any questions.

**Comment by lozaning** [comment]
BOM has been added to read me

**Comment by jrodriguezruibal** [comment]
Hi @lozaning , I'm a huge fan!

Thanks for your work. I think there's a typo in the BOM (copy&paste on microSD part mainly and not sure about the right adafruit ESP32S2 feather with TFT and there's 14 xiaos...). I'm trying to replicate it and I suggest this list (I guessed from your pics) that includes links:

- Adafruit GPS, 1 unit, "Adafruit Ultimate GPS Breakout - 66 channel w/10 Hz updates - PA1616S", https://www.adafruit.com/product/746 
- MicroSD reader, 1 unit, "MicroSD card breakout board+", https://www.adafruit.com/product/254
- Adafruit feather ESP32.S2, 1 unit, "Adafruit ESP32-S2 TFT Feather - 4MB Flash, 2MB PSRAM, STEMMA QT", https://www.adafruit.com/product/5300
- SeeedStudio Xiao, 14 units, (These can be any combination of the esp32-c3 or esp32-s3 ones. The benefits of the s3 is that it support BOTH BT and LE)
   - c3 model, https://www.seeedstudio.com/Seeed-XIAO-ESP32C3-p-5431.html
   - s3 model, https://www.seeedstudio.com/XIAO-ESP32S3-p-5627.html 

Thanks again for your work!
