### ISSUE TITLE
Unable to program feather esp32-s3 ESP8266WiFi.h not found

### ISSUE THREAD

**Issue by sardonyxserendil** [lozaning/The_Wifydra#3]
Hello!

I'm trying to flash the dom.ino file onto the feather ESP32-S3 TFT.  I'm using the espressif board URL located here thats referenced in adafruit's documentation:
https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_dev_index.json

Arduino IDE 2.02

I've selected the board 'Adafruit Feather ESP32-S3 TFT' but upon compliation I get the error:

```
/root/Arduino/Dom/Dom.ino:5:10: fatal error: ESP8266WiFi.h: No such file or directory
 #include <ESP8266WiFi.h>
          ^~~~~~~~~~~~~~~
compilation terminated.

exit status 1

Compilation error: ESP8266WiFi.h: No such file or directory
```

From what I can tell from a few google searches this library should be automatically loaded by board definition.  Is this the incorrect board?  If so, what is the correct one?  

One thing I also noticed is the dom.ino code seems to be much older than the sub.ino file.  Is this the correct code or is there a chance this library isn't actually used?

**Comment by lozaning** [comment]
Thanks for bringing this to my attention, I've swapped the library out for the correct wifi.h library and merged a new copy of Dom.ino to the repo. Can you try the new one and let me know if that one works for you?

**Comment by sardonyxserendil** [comment]
That resolved all problems and I was able to successfully flash the ESP32-S3 using the espressif board definition.  Thank you for all your work on this!
