### ISSUE TITLE
BOM has errors

### ISSUE THREAD

**Issue by sardonyxserendil** [lozaning/The_Wifydra#5]
Hello!

I believe the BOM on the main page has a few errors with the descriptions and part#'s.

1.  The BOM states using an ESP32-S2, however in your picture you used an ESP32-S3. 
2. The correct item# for the ESP32-S3 TFT is 5483
3. The SD card breakout board has the description of the GPS module.  The item# is 254
4. The GPS item# is 746

I just wanted to help out anyone else looking to make this project.  Thanks for all you do!

**Comment by lozaning** [comment]
Thanks, for the callout, fix'ed now.
